"use client";
import {useState,useEffect} from "react";
import {supabase} from "@/lib/supabase";
import LifePanel from "./life-panel";
import {jobGroups} from "./jobs";
type Career={role:string;cash:number;xp:number;level:number;started_at:string|null};
export default function WorldPanel({roomId}:{roomId:string}){
 const [job,setJob]=useState<Career|null>(null),[role,setRole]=useState("Police"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[body,setBody]=useState(""),[messages,setMessages]=useState<{id:number;username:string;body:string}[]>([]);
 useEffect(()=>{let alive=true;let timer:ReturnType<typeof setTimeout>;async function load(){if(!supabase)return;const [j,c]=await Promise.all([supabase.rpc('zion_job',{p_room:roomId}),supabase.rpc('zion_world_chat',{p_room:roomId})]);if(!alive)return;if(j.data)setJob(j.data);if(c.data)setMessages(c.data);timer=setTimeout(load,3000);}void load();return()=>{alive=false;clearTimeout(timer)}},[roomId]);
 async function action(name:string){if(!supabase||busy)return;setBusy(true);setError("");try{const {data,error}=await supabase.rpc('zion_job',{p_room:roomId,p_role:role,p_action:name});if(error)throw error;setJob(data);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function send(){if(!supabase||!body.trim()||busy)return;setBusy(true);setError("");try{const {data,error}=await supabase.rpc('zion_world_chat',{p_room:roomId,p_body:body});if(error)throw error;setMessages(data);setBody("");}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details id="zion-career-panel" className="world-career" onKeyDown={e=>e.stopPropagation()}><summary>Jobs & world chat • {job?.role||'Explorer'}</summary><p>Career savings ${job?.cash||0} · XP {job?.xp||0} · Level {job?.level||1}</p><label>Your job <select value={role} onChange={e=>setRole(e.target.value)}>{Object.entries(jobGroups).map(([g,list])=><optgroup key={g} label={g}>{list.map(n=><option key={n}>{n}</option>)}</optgroup>)}</select></label><button disabled={busy} onClick={()=>void action('choose')}>Choose / change job</button><p>Starter field assignment: start work, explore for 30 seconds and travel 20 metres away, then complete for $100 and 25 XP. Each role currently uses this introductory assignment.</p><button disabled={busy||!job||job.role==='Explorer'} onClick={()=>void action(job?.started_at?'complete':'start')}>{job?.started_at?'Complete assignment':'Start assignment'}</button><LifePanel key={roomId} roomId={roomId}/><p>Career savings pay for online services. The solo equipment wallet is separate.</p><h3>World chat</h3><small>Visible to this world’s players. Do not share private information.</small><div className="world-messages">{messages.map(m=><p key={m.id}><b>{m.username}: </b>{m.body}</p>)}</div><form onSubmit={e=>{e.preventDefault();void send()}}><input aria-label="World message" value={body} maxLength={500} onChange={e=>setBody(e.target.value)}/><button disabled={busy||!body.trim()}>Send</button></form>{error&&<p role="alert">{error}</p>}</details>
}
